{
 "title": "Elastic vs VLogs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "containers_selector", "query": ".*(vlogs|elastic|loki).*" },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name!=\"\",}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Filebeat items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(filebeat_libbeat_output_events{type=\"acked\"})) by (instance, type)",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\"})) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containers\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_disk_usage_bytes{path=~\"$containers_selector\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}