clients:  
  - url: http://loki:3100/loki/api/v1/push 
scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:12345
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
